remote_theme: "lewismiddleton/cayman-dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-responsive_image
  - emoji_for_jekyll
title: "Megan Moodie"
rss-description: "Megan Moodie"
description: "About Me"
author: "Megan Moodie"
back_to_top: true
back_to_top_text: "Back To Top"
gh_edit_link: false
permalink: pretty
