remote_theme: "Norok-The-Diablo/cayman-dark"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-responsive_image
  - emoji_for_jekyll
exclude:
  - _config.yml
  - README.md
  - LICENSE
title: "Megan Moodie"
rss-description: "Megan Moodie"
author: "Megan Moodie"
show_downloads: true
back_to_top: true
back_to_top_text: "Back To Top"
gh_edit_link: false
permalink: pretty
